/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.perrin.trains.ReseauRuntimeModule;
import fr.perrin.trains.ReseauStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ReseauIdeSetup extends ReseauStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ReseauRuntimeModule(), new ReseauIdeModule()));
	}
	
}
