/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau.impl;

import fr.perrin.trains.reseau.Ligne;
import fr.perrin.trains.reseau.Point;
import fr.perrin.trains.reseau.ReseauPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ligne</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.impl.LigneImpl#getP1 <em>P1</em>}</li>
 *   <li>{@link fr.perrin.trains.reseau.impl.LigneImpl#getP2 <em>P2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LigneImpl extends MinimalEObjectImpl.Container implements Ligne
{
  /**
   * The cached value of the '{@link #getP1() <em>P1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP1()
   * @generated
   * @ordered
   */
  protected Point p1;

  /**
   * The cached value of the '{@link #getP2() <em>P2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getP2()
   * @generated
   * @ordered
   */
  protected Point p2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LigneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReseauPackage.Literals.LIGNE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Point getP1()
  {
    return p1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetP1(Point newP1, NotificationChain msgs)
  {
    Point oldP1 = p1;
    p1 = newP1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ReseauPackage.LIGNE__P1, oldP1, newP1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP1(Point newP1)
  {
    if (newP1 != p1)
    {
      NotificationChain msgs = null;
      if (p1 != null)
        msgs = ((InternalEObject)p1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ReseauPackage.LIGNE__P1, null, msgs);
      if (newP1 != null)
        msgs = ((InternalEObject)newP1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ReseauPackage.LIGNE__P1, null, msgs);
      msgs = basicSetP1(newP1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReseauPackage.LIGNE__P1, newP1, newP1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Point getP2()
  {
    return p2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetP2(Point newP2, NotificationChain msgs)
  {
    Point oldP2 = p2;
    p2 = newP2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ReseauPackage.LIGNE__P2, oldP2, newP2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setP2(Point newP2)
  {
    if (newP2 != p2)
    {
      NotificationChain msgs = null;
      if (p2 != null)
        msgs = ((InternalEObject)p2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ReseauPackage.LIGNE__P2, null, msgs);
      if (newP2 != null)
        msgs = ((InternalEObject)newP2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ReseauPackage.LIGNE__P2, null, msgs);
      msgs = basicSetP2(newP2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReseauPackage.LIGNE__P2, newP2, newP2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ReseauPackage.LIGNE__P1:
        return basicSetP1(null, msgs);
      case ReseauPackage.LIGNE__P2:
        return basicSetP2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ReseauPackage.LIGNE__P1:
        return getP1();
      case ReseauPackage.LIGNE__P2:
        return getP2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ReseauPackage.LIGNE__P1:
        setP1((Point)newValue);
        return;
      case ReseauPackage.LIGNE__P2:
        setP2((Point)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ReseauPackage.LIGNE__P1:
        setP1((Point)null);
        return;
      case ReseauPackage.LIGNE__P2:
        setP2((Point)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ReseauPackage.LIGNE__P1:
        return p1 != null;
      case ReseauPackage.LIGNE__P2:
        return p2 != null;
    }
    return super.eIsSet(featureID);
  }

} //LigneImpl
