/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ReseauStandaloneSetup extends ReseauStandaloneSetupGenerated {

	public static void doSetup() {
		new ReseauStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
