/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReseauAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/perrin/trains/parser/antlr/internal/InternalReseau.tokens");
	}
}
