/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.parser.antlr;

import com.google.inject.Inject;
import fr.perrin.trains.parser.antlr.internal.InternalReseauParser;
import fr.perrin.trains.services.ReseauGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ReseauParser extends AbstractAntlrParser {

	@Inject
	private ReseauGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReseauParser createParser(XtextTokenStream stream) {
		return new InternalReseauParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ReseauGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReseauGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
