/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReseauScopeProvider extends DelegatingScopeProvider {
}
