/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bidir</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.Bidir#getPts <em>Pts</em>}</li>
 * </ul>
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getBidir()
 * @model
 * @generated
 */
public interface Bidir extends EObject
{
  /**
   * Returns the value of the '<em><b>Pts</b></em>' containment reference list.
   * The list contents are of type {@link fr.perrin.trains.reseau.Point}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pts</em>' containment reference list.
   * @see fr.perrin.trains.reseau.ReseauPackage#getBidir_Pts()
   * @model containment="true"
   * @generated
   */
  EList<Point> getPts();

} // Bidir
