/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declared</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.Declared#getDecl <em>Decl</em>}</li>
 * </ul>
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getDeclared()
 * @model
 * @generated
 */
public interface Declared extends Point
{
  /**
   * Returns the value of the '<em><b>Decl</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl</em>' reference.
   * @see #setDecl(DeclarationPoint)
   * @see fr.perrin.trains.reseau.ReseauPackage#getDeclared_Decl()
   * @model
   * @generated
   */
  DeclarationPoint getDecl();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.Declared#getDecl <em>Decl</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decl</em>' reference.
   * @see #getDecl()
   * @generated
   */
  void setDecl(DeclarationPoint value);

} // Declared
