/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intersection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.Intersection#getL1 <em>L1</em>}</li>
 *   <li>{@link fr.perrin.trains.reseau.Intersection#getL2 <em>L2</em>}</li>
 * </ul>
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getIntersection()
 * @model
 * @generated
 */
public interface Intersection extends Point
{
  /**
   * Returns the value of the '<em><b>L1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L1</em>' containment reference.
   * @see #setL1(Ligne)
   * @see fr.perrin.trains.reseau.ReseauPackage#getIntersection_L1()
   * @model containment="true"
   * @generated
   */
  Ligne getL1();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.Intersection#getL1 <em>L1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L1</em>' containment reference.
   * @see #getL1()
   * @generated
   */
  void setL1(Ligne value);

  /**
   * Returns the value of the '<em><b>L2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L2</em>' containment reference.
   * @see #setL2(Ligne)
   * @see fr.perrin.trains.reseau.ReseauPackage#getIntersection_L2()
   * @model containment="true"
   * @generated
   */
  Ligne getL2();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.Intersection#getL2 <em>L2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L2</em>' containment reference.
   * @see #getL2()
   * @generated
   */
  void setL2(Ligne value);

} // Intersection
