/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ligne1</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getLigne1()
 * @model
 * @generated
 */
public interface Ligne1 extends Ligne
{
} // Ligne1
