/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ligne2</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getLigne2()
 * @model
 * @generated
 */
public interface Ligne2 extends Ligne
{
} // Ligne2
