/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ligne</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.Ligne#getP1 <em>P1</em>}</li>
 *   <li>{@link fr.perrin.trains.reseau.Ligne#getP2 <em>P2</em>}</li>
 * </ul>
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getLigne()
 * @model
 * @generated
 */
public interface Ligne extends EObject
{
  /**
   * Returns the value of the '<em><b>P1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P1</em>' containment reference.
   * @see #setP1(Point)
   * @see fr.perrin.trains.reseau.ReseauPackage#getLigne_P1()
   * @model containment="true"
   * @generated
   */
  Point getP1();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.Ligne#getP1 <em>P1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P1</em>' containment reference.
   * @see #getP1()
   * @generated
   */
  void setP1(Point value);

  /**
   * Returns the value of the '<em><b>P2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P2</em>' containment reference.
   * @see #setP2(Point)
   * @see fr.perrin.trains.reseau.ReseauPackage#getLigne_P2()
   * @model containment="true"
   * @generated
   */
  Point getP2();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.Ligne#getP2 <em>P2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>P2</em>' containment reference.
   * @see #getP2()
   * @generated
   */
  void setP2(Point value);

} // Ligne
