/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.Model#getSegments <em>Segments</em>}</li>
 *   <li>{@link fr.perrin.trains.reseau.Model#getPointsLiaison <em>Points Liaison</em>}</li>
 * </ul>
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Segments</b></em>' containment reference list.
   * The list contents are of type {@link fr.perrin.trains.reseau.Segment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segments</em>' containment reference list.
   * @see fr.perrin.trains.reseau.ReseauPackage#getModel_Segments()
   * @model containment="true"
   * @generated
   */
  EList<Segment> getSegments();

  /**
   * Returns the value of the '<em><b>Points Liaison</b></em>' containment reference list.
   * The list contents are of type {@link fr.perrin.trains.reseau.DeclarationPoint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points Liaison</em>' containment reference list.
   * @see fr.perrin.trains.reseau.ReseauPackage#getModel_PointsLiaison()
   * @model containment="true"
   * @generated
   */
  EList<DeclarationPoint> getPointsLiaison();

} // Model
