/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getPoint()
 * @model
 * @generated
 */
public interface Point extends EObject
{
} // Point
