/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.perrin.trains.reseau.ReseauFactory
 * @model kind="package"
 * @generated
 */
public interface ReseauPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reseau";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.perrin.fr/trains/Reseau";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reseau";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReseauPackage eINSTANCE = fr.perrin.trains.reseau.impl.ReseauPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.ModelImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Segments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SEGMENTS = 0;

  /**
   * The feature id for the '<em><b>Points Liaison</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__POINTS_LIAISON = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.DeclarationPointImpl <em>Declaration Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.DeclarationPointImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDeclarationPoint()
   * @generated
   */
  int DECLARATION_POINT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_POINT__NAME = 0;

  /**
   * The feature id for the '<em><b>Xy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_POINT__XY = 1;

  /**
   * The number of structural features of the '<em>Declaration Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_POINT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.PointImpl <em>Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.PointImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPoint()
   * @generated
   */
  int POINT = 2;

  /**
   * The number of structural features of the '<em>Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.LigneImpl <em>Ligne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.LigneImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLigne()
   * @generated
   */
  int LIGNE = 3;

  /**
   * The feature id for the '<em><b>P1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE__P1 = 0;

  /**
   * The feature id for the '<em><b>P2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE__P2 = 1;

  /**
   * The number of structural features of the '<em>Ligne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.Ligne1Impl <em>Ligne1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.Ligne1Impl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLigne1()
   * @generated
   */
  int LIGNE1 = 4;

  /**
   * The feature id for the '<em><b>P1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE1__P1 = LIGNE__P1;

  /**
   * The feature id for the '<em><b>P2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE1__P2 = LIGNE__P2;

  /**
   * The number of structural features of the '<em>Ligne1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE1_FEATURE_COUNT = LIGNE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.Ligne2Impl <em>Ligne2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.Ligne2Impl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLigne2()
   * @generated
   */
  int LIGNE2 = 5;

  /**
   * The feature id for the '<em><b>P1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE2__P1 = LIGNE__P1;

  /**
   * The feature id for the '<em><b>P2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE2__P2 = LIGNE__P2;

  /**
   * The number of structural features of the '<em>Ligne2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE2_FEATURE_COUNT = LIGNE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.SegmentImpl <em>Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.SegmentImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getSegment()
   * @generated
   */
  int SEGMENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEGMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Parts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEGMENT__PARTS = 1;

  /**
   * The number of structural features of the '<em>Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEGMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.SegmentPartImpl <em>Segment Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.SegmentPartImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getSegmentPart()
   * @generated
   */
  int SEGMENT_PART = 7;

  /**
   * The feature id for the '<em><b>Fst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEGMENT_PART__FST = 0;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEGMENT_PART__NEXT = 1;

  /**
   * The number of structural features of the '<em>Segment Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEGMENT_PART_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.UnidirImpl <em>Unidir</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.UnidirImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getUnidir()
   * @generated
   */
  int UNIDIR = 8;

  /**
   * The feature id for the '<em><b>Pts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIDIR__PTS = 0;

  /**
   * The number of structural features of the '<em>Unidir</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIDIR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.BidirImpl <em>Bidir</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.BidirImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getBidir()
   * @generated
   */
  int BIDIR = 9;

  /**
   * The feature id for the '<em><b>Pts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIDIR__PTS = 0;

  /**
   * The number of structural features of the '<em>Bidir</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIDIR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.PlusImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPlus()
   * @generated
   */
  int PLUS = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.MinusImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getMinus()
   * @generated
   */
  int MINUS = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.MultiImpl <em>Multi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.MultiImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getMulti()
   * @generated
   */
  int MULTI = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__RIGHT = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.DivImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDiv()
   * @generated
   */
  int DIV = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__RIGHT = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.DegreeImpl <em>Degree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.DegreeImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDegree()
   * @generated
   */
  int DEGREE = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Degree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEGREE_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.PowImpl <em>Pow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.PowImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPow()
   * @generated
   */
  int POW = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POW__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POW__RIGHT = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Pow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POW_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.CoordonneeLiteralImpl <em>Coordonnee Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.CoordonneeLiteralImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getCoordonneeLiteral()
   * @generated
   */
  int COORDONNEE_LITERAL = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDONNEE_LITERAL__LEFT = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDONNEE_LITERAL__RIGHT = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Coordonnee Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDONNEE_LITERAL_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.NumberLiteralImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.NegativeImpl <em>Negative</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.NegativeImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getNegative()
   * @generated
   */
  int NEGATIVE = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATIVE__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Negative</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATIVE_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.DeclaredImpl <em>Declared</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.DeclaredImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDeclared()
   * @generated
   */
  int DECLARED = 19;

  /**
   * The feature id for the '<em><b>Decl</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARED__DECL = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Declared</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARED_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.DernierImpl <em>Dernier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.DernierImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDernier()
   * @generated
   */
  int DERNIER = 20;

  /**
   * The number of structural features of the '<em>Dernier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERNIER_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.NordImpl <em>Nord</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.NordImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getNord()
   * @generated
   */
  int NORD = 21;

  /**
   * The number of structural features of the '<em>Nord</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORD_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.SudImpl <em>Sud</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.SudImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getSud()
   * @generated
   */
  int SUD = 22;

  /**
   * The number of structural features of the '<em>Sud</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUD_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.EstImpl <em>Est</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.EstImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getEst()
   * @generated
   */
  int EST = 23;

  /**
   * The number of structural features of the '<em>Est</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EST_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.OuestImpl <em>Ouest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.OuestImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getOuest()
   * @generated
   */
  int OUEST = 24;

  /**
   * The number of structural features of the '<em>Ouest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUEST_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.PiImpl <em>Pi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.PiImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPi()
   * @generated
   */
  int PI = 25;

  /**
   * The number of structural features of the '<em>Pi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PI_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.EulerImpl <em>Euler</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.EulerImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getEuler()
   * @generated
   */
  int EULER = 26;

  /**
   * The number of structural features of the '<em>Euler</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EULER_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.IImpl <em>I</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.IImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getI()
   * @generated
   */
  int I = 27;

  /**
   * The number of structural features of the '<em>I</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int I_FEATURE_COUNT = POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.XImpl <em>X</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.XImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getX()
   * @generated
   */
  int X = 28;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int X__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>X</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int X_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.YImpl <em>Y</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.YImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getY()
   * @generated
   */
  int Y = 29;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Y</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.LongueurImpl <em>Longueur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.LongueurImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLongueur()
   * @generated
   */
  int LONGUEUR = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONGUEUR__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Longueur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONGUEUR_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.AngleImpl <em>Angle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.AngleImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getAngle()
   * @generated
   */
  int ANGLE = 31;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANGLE__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Angle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANGLE_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.ArgumentImpl <em>Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.ArgumentImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getArgument()
   * @generated
   */
  int ARGUMENT = 32;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__VALUE = POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_FEATURE_COUNT = POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.perrin.trains.reseau.impl.IntersectionImpl <em>Intersection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.perrin.trains.reseau.impl.IntersectionImpl
   * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getIntersection()
   * @generated
   */
  int INTERSECTION = 33;

  /**
   * The feature id for the '<em><b>L1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION__L1 = POINT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>L2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION__L2 = POINT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Intersection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION_FEATURE_COUNT = POINT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.perrin.trains.reseau.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.perrin.trains.reseau.Model#getSegments <em>Segments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Segments</em>'.
   * @see fr.perrin.trains.reseau.Model#getSegments()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Segments();

  /**
   * Returns the meta object for the containment reference list '{@link fr.perrin.trains.reseau.Model#getPointsLiaison <em>Points Liaison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Points Liaison</em>'.
   * @see fr.perrin.trains.reseau.Model#getPointsLiaison()
   * @see #getModel()
   * @generated
   */
  EReference getModel_PointsLiaison();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.DeclarationPoint <em>Declaration Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration Point</em>'.
   * @see fr.perrin.trains.reseau.DeclarationPoint
   * @generated
   */
  EClass getDeclarationPoint();

  /**
   * Returns the meta object for the attribute '{@link fr.perrin.trains.reseau.DeclarationPoint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.perrin.trains.reseau.DeclarationPoint#getName()
   * @see #getDeclarationPoint()
   * @generated
   */
  EAttribute getDeclarationPoint_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.DeclarationPoint#getXy <em>Xy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xy</em>'.
   * @see fr.perrin.trains.reseau.DeclarationPoint#getXy()
   * @see #getDeclarationPoint()
   * @generated
   */
  EReference getDeclarationPoint_Xy();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Point <em>Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Point</em>'.
   * @see fr.perrin.trains.reseau.Point
   * @generated
   */
  EClass getPoint();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Ligne <em>Ligne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne</em>'.
   * @see fr.perrin.trains.reseau.Ligne
   * @generated
   */
  EClass getLigne();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Ligne#getP1 <em>P1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>P1</em>'.
   * @see fr.perrin.trains.reseau.Ligne#getP1()
   * @see #getLigne()
   * @generated
   */
  EReference getLigne_P1();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Ligne#getP2 <em>P2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>P2</em>'.
   * @see fr.perrin.trains.reseau.Ligne#getP2()
   * @see #getLigne()
   * @generated
   */
  EReference getLigne_P2();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Ligne1 <em>Ligne1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne1</em>'.
   * @see fr.perrin.trains.reseau.Ligne1
   * @generated
   */
  EClass getLigne1();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Ligne2 <em>Ligne2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne2</em>'.
   * @see fr.perrin.trains.reseau.Ligne2
   * @generated
   */
  EClass getLigne2();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Segment <em>Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Segment</em>'.
   * @see fr.perrin.trains.reseau.Segment
   * @generated
   */
  EClass getSegment();

  /**
   * Returns the meta object for the attribute '{@link fr.perrin.trains.reseau.Segment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.perrin.trains.reseau.Segment#getName()
   * @see #getSegment()
   * @generated
   */
  EAttribute getSegment_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.perrin.trains.reseau.Segment#getParts <em>Parts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parts</em>'.
   * @see fr.perrin.trains.reseau.Segment#getParts()
   * @see #getSegment()
   * @generated
   */
  EReference getSegment_Parts();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.SegmentPart <em>Segment Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Segment Part</em>'.
   * @see fr.perrin.trains.reseau.SegmentPart
   * @generated
   */
  EClass getSegmentPart();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.SegmentPart#getFst <em>Fst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fst</em>'.
   * @see fr.perrin.trains.reseau.SegmentPart#getFst()
   * @see #getSegmentPart()
   * @generated
   */
  EReference getSegmentPart_Fst();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.SegmentPart#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see fr.perrin.trains.reseau.SegmentPart#getNext()
   * @see #getSegmentPart()
   * @generated
   */
  EReference getSegmentPart_Next();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Unidir <em>Unidir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unidir</em>'.
   * @see fr.perrin.trains.reseau.Unidir
   * @generated
   */
  EClass getUnidir();

  /**
   * Returns the meta object for the containment reference list '{@link fr.perrin.trains.reseau.Unidir#getPts <em>Pts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pts</em>'.
   * @see fr.perrin.trains.reseau.Unidir#getPts()
   * @see #getUnidir()
   * @generated
   */
  EReference getUnidir_Pts();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Bidir <em>Bidir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bidir</em>'.
   * @see fr.perrin.trains.reseau.Bidir
   * @generated
   */
  EClass getBidir();

  /**
   * Returns the meta object for the containment reference list '{@link fr.perrin.trains.reseau.Bidir#getPts <em>Pts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pts</em>'.
   * @see fr.perrin.trains.reseau.Bidir#getPts()
   * @see #getBidir()
   * @generated
   */
  EReference getBidir_Pts();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see fr.perrin.trains.reseau.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.perrin.trains.reseau.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see fr.perrin.trains.reseau.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.perrin.trains.reseau.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Multi <em>Multi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multi</em>'.
   * @see fr.perrin.trains.reseau.Multi
   * @generated
   */
  EClass getMulti();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Multi#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.Multi#getLeft()
   * @see #getMulti()
   * @generated
   */
  EReference getMulti_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Multi#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.perrin.trains.reseau.Multi#getRight()
   * @see #getMulti()
   * @generated
   */
  EReference getMulti_Right();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see fr.perrin.trains.reseau.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Div#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.Div#getLeft()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Div#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.perrin.trains.reseau.Div#getRight()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Right();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Degree <em>Degree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Degree</em>'.
   * @see fr.perrin.trains.reseau.Degree
   * @generated
   */
  EClass getDegree();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Degree#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.Degree#getLeft()
   * @see #getDegree()
   * @generated
   */
  EReference getDegree_Left();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Pow <em>Pow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pow</em>'.
   * @see fr.perrin.trains.reseau.Pow
   * @generated
   */
  EClass getPow();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Pow#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.Pow#getLeft()
   * @see #getPow()
   * @generated
   */
  EReference getPow_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Pow#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.perrin.trains.reseau.Pow#getRight()
   * @see #getPow()
   * @generated
   */
  EReference getPow_Right();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.CoordonneeLiteral <em>Coordonnee Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordonnee Literal</em>'.
   * @see fr.perrin.trains.reseau.CoordonneeLiteral
   * @generated
   */
  EClass getCoordonneeLiteral();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.CoordonneeLiteral#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.perrin.trains.reseau.CoordonneeLiteral#getLeft()
   * @see #getCoordonneeLiteral()
   * @generated
   */
  EReference getCoordonneeLiteral_Left();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.CoordonneeLiteral#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.perrin.trains.reseau.CoordonneeLiteral#getRight()
   * @see #getCoordonneeLiteral()
   * @generated
   */
  EReference getCoordonneeLiteral_Right();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see fr.perrin.trains.reseau.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link fr.perrin.trains.reseau.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Negative <em>Negative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negative</em>'.
   * @see fr.perrin.trains.reseau.Negative
   * @generated
   */
  EClass getNegative();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Negative#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.Negative#getValue()
   * @see #getNegative()
   * @generated
   */
  EReference getNegative_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Declared <em>Declared</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declared</em>'.
   * @see fr.perrin.trains.reseau.Declared
   * @generated
   */
  EClass getDeclared();

  /**
   * Returns the meta object for the reference '{@link fr.perrin.trains.reseau.Declared#getDecl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Decl</em>'.
   * @see fr.perrin.trains.reseau.Declared#getDecl()
   * @see #getDeclared()
   * @generated
   */
  EReference getDeclared_Decl();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Dernier <em>Dernier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dernier</em>'.
   * @see fr.perrin.trains.reseau.Dernier
   * @generated
   */
  EClass getDernier();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Nord <em>Nord</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nord</em>'.
   * @see fr.perrin.trains.reseau.Nord
   * @generated
   */
  EClass getNord();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Sud <em>Sud</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sud</em>'.
   * @see fr.perrin.trains.reseau.Sud
   * @generated
   */
  EClass getSud();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Est <em>Est</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Est</em>'.
   * @see fr.perrin.trains.reseau.Est
   * @generated
   */
  EClass getEst();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Ouest <em>Ouest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ouest</em>'.
   * @see fr.perrin.trains.reseau.Ouest
   * @generated
   */
  EClass getOuest();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Pi <em>Pi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pi</em>'.
   * @see fr.perrin.trains.reseau.Pi
   * @generated
   */
  EClass getPi();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Euler <em>Euler</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Euler</em>'.
   * @see fr.perrin.trains.reseau.Euler
   * @generated
   */
  EClass getEuler();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.I <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>I</em>'.
   * @see fr.perrin.trains.reseau.I
   * @generated
   */
  EClass getI();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.X <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>X</em>'.
   * @see fr.perrin.trains.reseau.X
   * @generated
   */
  EClass getX();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.X#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.X#getValue()
   * @see #getX()
   * @generated
   */
  EReference getX_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Y <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Y</em>'.
   * @see fr.perrin.trains.reseau.Y
   * @generated
   */
  EClass getY();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Y#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.Y#getValue()
   * @see #getY()
   * @generated
   */
  EReference getY_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Longueur <em>Longueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Longueur</em>'.
   * @see fr.perrin.trains.reseau.Longueur
   * @generated
   */
  EClass getLongueur();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Longueur#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.Longueur#getValue()
   * @see #getLongueur()
   * @generated
   */
  EReference getLongueur_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Angle <em>Angle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Angle</em>'.
   * @see fr.perrin.trains.reseau.Angle
   * @generated
   */
  EClass getAngle();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Angle#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.Angle#getValue()
   * @see #getAngle()
   * @generated
   */
  EReference getAngle_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Argument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argument</em>'.
   * @see fr.perrin.trains.reseau.Argument
   * @generated
   */
  EClass getArgument();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Argument#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.perrin.trains.reseau.Argument#getValue()
   * @see #getArgument()
   * @generated
   */
  EReference getArgument_Value();

  /**
   * Returns the meta object for class '{@link fr.perrin.trains.reseau.Intersection <em>Intersection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intersection</em>'.
   * @see fr.perrin.trains.reseau.Intersection
   * @generated
   */
  EClass getIntersection();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Intersection#getL1 <em>L1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>L1</em>'.
   * @see fr.perrin.trains.reseau.Intersection#getL1()
   * @see #getIntersection()
   * @generated
   */
  EReference getIntersection_L1();

  /**
   * Returns the meta object for the containment reference '{@link fr.perrin.trains.reseau.Intersection#getL2 <em>L2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>L2</em>'.
   * @see fr.perrin.trains.reseau.Intersection#getL2()
   * @see #getIntersection()
   * @generated
   */
  EReference getIntersection_L2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReseauFactory getReseauFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.ModelImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Segments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SEGMENTS = eINSTANCE.getModel_Segments();

    /**
     * The meta object literal for the '<em><b>Points Liaison</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__POINTS_LIAISON = eINSTANCE.getModel_PointsLiaison();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.DeclarationPointImpl <em>Declaration Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.DeclarationPointImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDeclarationPoint()
     * @generated
     */
    EClass DECLARATION_POINT = eINSTANCE.getDeclarationPoint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION_POINT__NAME = eINSTANCE.getDeclarationPoint_Name();

    /**
     * The meta object literal for the '<em><b>Xy</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION_POINT__XY = eINSTANCE.getDeclarationPoint_Xy();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.PointImpl <em>Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.PointImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPoint()
     * @generated
     */
    EClass POINT = eINSTANCE.getPoint();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.LigneImpl <em>Ligne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.LigneImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLigne()
     * @generated
     */
    EClass LIGNE = eINSTANCE.getLigne();

    /**
     * The meta object literal for the '<em><b>P1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGNE__P1 = eINSTANCE.getLigne_P1();

    /**
     * The meta object literal for the '<em><b>P2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGNE__P2 = eINSTANCE.getLigne_P2();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.Ligne1Impl <em>Ligne1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.Ligne1Impl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLigne1()
     * @generated
     */
    EClass LIGNE1 = eINSTANCE.getLigne1();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.Ligne2Impl <em>Ligne2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.Ligne2Impl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLigne2()
     * @generated
     */
    EClass LIGNE2 = eINSTANCE.getLigne2();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.SegmentImpl <em>Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.SegmentImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getSegment()
     * @generated
     */
    EClass SEGMENT = eINSTANCE.getSegment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEGMENT__NAME = eINSTANCE.getSegment_Name();

    /**
     * The meta object literal for the '<em><b>Parts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEGMENT__PARTS = eINSTANCE.getSegment_Parts();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.SegmentPartImpl <em>Segment Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.SegmentPartImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getSegmentPart()
     * @generated
     */
    EClass SEGMENT_PART = eINSTANCE.getSegmentPart();

    /**
     * The meta object literal for the '<em><b>Fst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEGMENT_PART__FST = eINSTANCE.getSegmentPart_Fst();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEGMENT_PART__NEXT = eINSTANCE.getSegmentPart_Next();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.UnidirImpl <em>Unidir</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.UnidirImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getUnidir()
     * @generated
     */
    EClass UNIDIR = eINSTANCE.getUnidir();

    /**
     * The meta object literal for the '<em><b>Pts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNIDIR__PTS = eINSTANCE.getUnidir_Pts();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.BidirImpl <em>Bidir</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.BidirImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getBidir()
     * @generated
     */
    EClass BIDIR = eINSTANCE.getBidir();

    /**
     * The meta object literal for the '<em><b>Pts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BIDIR__PTS = eINSTANCE.getBidir_Pts();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.PlusImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.MinusImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.MultiImpl <em>Multi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.MultiImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getMulti()
     * @generated
     */
    EClass MULTI = eINSTANCE.getMulti();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTI__LEFT = eINSTANCE.getMulti_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTI__RIGHT = eINSTANCE.getMulti_Right();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.DivImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__LEFT = eINSTANCE.getDiv_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__RIGHT = eINSTANCE.getDiv_Right();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.DegreeImpl <em>Degree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.DegreeImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDegree()
     * @generated
     */
    EClass DEGREE = eINSTANCE.getDegree();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEGREE__LEFT = eINSTANCE.getDegree_Left();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.PowImpl <em>Pow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.PowImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPow()
     * @generated
     */
    EClass POW = eINSTANCE.getPow();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POW__LEFT = eINSTANCE.getPow_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POW__RIGHT = eINSTANCE.getPow_Right();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.CoordonneeLiteralImpl <em>Coordonnee Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.CoordonneeLiteralImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getCoordonneeLiteral()
     * @generated
     */
    EClass COORDONNEE_LITERAL = eINSTANCE.getCoordonneeLiteral();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COORDONNEE_LITERAL__LEFT = eINSTANCE.getCoordonneeLiteral_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COORDONNEE_LITERAL__RIGHT = eINSTANCE.getCoordonneeLiteral_Right();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.NumberLiteralImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.NegativeImpl <em>Negative</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.NegativeImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getNegative()
     * @generated
     */
    EClass NEGATIVE = eINSTANCE.getNegative();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEGATIVE__VALUE = eINSTANCE.getNegative_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.DeclaredImpl <em>Declared</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.DeclaredImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDeclared()
     * @generated
     */
    EClass DECLARED = eINSTANCE.getDeclared();

    /**
     * The meta object literal for the '<em><b>Decl</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARED__DECL = eINSTANCE.getDeclared_Decl();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.DernierImpl <em>Dernier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.DernierImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getDernier()
     * @generated
     */
    EClass DERNIER = eINSTANCE.getDernier();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.NordImpl <em>Nord</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.NordImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getNord()
     * @generated
     */
    EClass NORD = eINSTANCE.getNord();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.SudImpl <em>Sud</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.SudImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getSud()
     * @generated
     */
    EClass SUD = eINSTANCE.getSud();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.EstImpl <em>Est</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.EstImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getEst()
     * @generated
     */
    EClass EST = eINSTANCE.getEst();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.OuestImpl <em>Ouest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.OuestImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getOuest()
     * @generated
     */
    EClass OUEST = eINSTANCE.getOuest();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.PiImpl <em>Pi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.PiImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getPi()
     * @generated
     */
    EClass PI = eINSTANCE.getPi();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.EulerImpl <em>Euler</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.EulerImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getEuler()
     * @generated
     */
    EClass EULER = eINSTANCE.getEuler();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.IImpl <em>I</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.IImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getI()
     * @generated
     */
    EClass I = eINSTANCE.getI();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.XImpl <em>X</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.XImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getX()
     * @generated
     */
    EClass X = eINSTANCE.getX();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference X__VALUE = eINSTANCE.getX_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.YImpl <em>Y</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.YImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getY()
     * @generated
     */
    EClass Y = eINSTANCE.getY();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference Y__VALUE = eINSTANCE.getY_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.LongueurImpl <em>Longueur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.LongueurImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getLongueur()
     * @generated
     */
    EClass LONGUEUR = eINSTANCE.getLongueur();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LONGUEUR__VALUE = eINSTANCE.getLongueur_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.AngleImpl <em>Angle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.AngleImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getAngle()
     * @generated
     */
    EClass ANGLE = eINSTANCE.getAngle();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANGLE__VALUE = eINSTANCE.getAngle_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.ArgumentImpl <em>Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.ArgumentImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getArgument()
     * @generated
     */
    EClass ARGUMENT = eINSTANCE.getArgument();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENT__VALUE = eINSTANCE.getArgument_Value();

    /**
     * The meta object literal for the '{@link fr.perrin.trains.reseau.impl.IntersectionImpl <em>Intersection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.perrin.trains.reseau.impl.IntersectionImpl
     * @see fr.perrin.trains.reseau.impl.ReseauPackageImpl#getIntersection()
     * @generated
     */
    EClass INTERSECTION = eINSTANCE.getIntersection();

    /**
     * The meta object literal for the '<em><b>L1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERSECTION__L1 = eINSTANCE.getIntersection_L1();

    /**
     * The meta object literal for the '<em><b>L2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERSECTION__L2 = eINSTANCE.getIntersection_L2();

  }

} //ReseauPackage
