/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.perrin.trains.reseau.ReseauPackage
 * @generated
 */
public interface ReseauFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReseauFactory eINSTANCE = fr.perrin.trains.reseau.impl.ReseauFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Declaration Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration Point</em>'.
   * @generated
   */
  DeclarationPoint createDeclarationPoint();

  /**
   * Returns a new object of class '<em>Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Point</em>'.
   * @generated
   */
  Point createPoint();

  /**
   * Returns a new object of class '<em>Ligne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne</em>'.
   * @generated
   */
  Ligne createLigne();

  /**
   * Returns a new object of class '<em>Ligne1</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne1</em>'.
   * @generated
   */
  Ligne1 createLigne1();

  /**
   * Returns a new object of class '<em>Ligne2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligne2</em>'.
   * @generated
   */
  Ligne2 createLigne2();

  /**
   * Returns a new object of class '<em>Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Segment</em>'.
   * @generated
   */
  Segment createSegment();

  /**
   * Returns a new object of class '<em>Segment Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Segment Part</em>'.
   * @generated
   */
  SegmentPart createSegmentPart();

  /**
   * Returns a new object of class '<em>Unidir</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unidir</em>'.
   * @generated
   */
  Unidir createUnidir();

  /**
   * Returns a new object of class '<em>Bidir</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bidir</em>'.
   * @generated
   */
  Bidir createBidir();

  /**
   * Returns a new object of class '<em>Plus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plus</em>'.
   * @generated
   */
  Plus createPlus();

  /**
   * Returns a new object of class '<em>Minus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Minus</em>'.
   * @generated
   */
  Minus createMinus();

  /**
   * Returns a new object of class '<em>Multi</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multi</em>'.
   * @generated
   */
  Multi createMulti();

  /**
   * Returns a new object of class '<em>Div</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Div</em>'.
   * @generated
   */
  Div createDiv();

  /**
   * Returns a new object of class '<em>Degree</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Degree</em>'.
   * @generated
   */
  Degree createDegree();

  /**
   * Returns a new object of class '<em>Pow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pow</em>'.
   * @generated
   */
  Pow createPow();

  /**
   * Returns a new object of class '<em>Coordonnee Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Coordonnee Literal</em>'.
   * @generated
   */
  CoordonneeLiteral createCoordonneeLiteral();

  /**
   * Returns a new object of class '<em>Number Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Number Literal</em>'.
   * @generated
   */
  NumberLiteral createNumberLiteral();

  /**
   * Returns a new object of class '<em>Negative</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Negative</em>'.
   * @generated
   */
  Negative createNegative();

  /**
   * Returns a new object of class '<em>Declared</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declared</em>'.
   * @generated
   */
  Declared createDeclared();

  /**
   * Returns a new object of class '<em>Dernier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dernier</em>'.
   * @generated
   */
  Dernier createDernier();

  /**
   * Returns a new object of class '<em>Nord</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nord</em>'.
   * @generated
   */
  Nord createNord();

  /**
   * Returns a new object of class '<em>Sud</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sud</em>'.
   * @generated
   */
  Sud createSud();

  /**
   * Returns a new object of class '<em>Est</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Est</em>'.
   * @generated
   */
  Est createEst();

  /**
   * Returns a new object of class '<em>Ouest</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ouest</em>'.
   * @generated
   */
  Ouest createOuest();

  /**
   * Returns a new object of class '<em>Pi</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pi</em>'.
   * @generated
   */
  Pi createPi();

  /**
   * Returns a new object of class '<em>Euler</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Euler</em>'.
   * @generated
   */
  Euler createEuler();

  /**
   * Returns a new object of class '<em>I</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>I</em>'.
   * @generated
   */
  I createI();

  /**
   * Returns a new object of class '<em>X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>X</em>'.
   * @generated
   */
  X createX();

  /**
   * Returns a new object of class '<em>Y</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Y</em>'.
   * @generated
   */
  Y createY();

  /**
   * Returns a new object of class '<em>Longueur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Longueur</em>'.
   * @generated
   */
  Longueur createLongueur();

  /**
   * Returns a new object of class '<em>Angle</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Angle</em>'.
   * @generated
   */
  Angle createAngle();

  /**
   * Returns a new object of class '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument</em>'.
   * @generated
   */
  Argument createArgument();

  /**
   * Returns a new object of class '<em>Intersection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Intersection</em>'.
   * @generated
   */
  Intersection createIntersection();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReseauPackage getReseauPackage();

} //ReseauFactory
