/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Segment Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.perrin.trains.reseau.SegmentPart#getFst <em>Fst</em>}</li>
 *   <li>{@link fr.perrin.trains.reseau.SegmentPart#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getSegmentPart()
 * @model
 * @generated
 */
public interface SegmentPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Fst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fst</em>' containment reference.
   * @see #setFst(Point)
   * @see fr.perrin.trains.reseau.ReseauPackage#getSegmentPart_Fst()
   * @model containment="true"
   * @generated
   */
  Point getFst();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.SegmentPart#getFst <em>Fst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fst</em>' containment reference.
   * @see #getFst()
   * @generated
   */
  void setFst(Point value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(EObject)
   * @see fr.perrin.trains.reseau.ReseauPackage#getSegmentPart_Next()
   * @model containment="true"
   * @generated
   */
  EObject getNext();

  /**
   * Sets the value of the '{@link fr.perrin.trains.reseau.SegmentPart#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(EObject value);

} // SegmentPart
