/**
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.reseau;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sud</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.perrin.trains.reseau.ReseauPackage#getSud()
 * @model
 * @generated
 */
public interface Sud extends Point
{
} // Sud
