/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.ui.tests;

import com.google.inject.Injector;
import fr.perrin.trains.reseau.ui.internal.ReseauActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ReseauUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ReseauActivator.getInstance().getInjector("fr.perrin.trains.Reseau");
	}

}
