/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.serializer;

import com.google.inject.Inject;
import fr.perrin.trains.services.ReseauGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class ReseauSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ReseauGrammarAccess grammarAccess;
	protected AbstractElementAlias match_PrimaryExpression_LeftParenthesisKeyword_0_0_a;
	protected AbstractElementAlias match_PrimaryExpression_LeftParenthesisKeyword_0_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ReseauGrammarAccess) access;
		match_PrimaryExpression_LeftParenthesisKeyword_0_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_0_0());
		match_PrimaryExpression_LeftParenthesisKeyword_0_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_0_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_PrimaryExpression_LeftParenthesisKeyword_0_0_a.equals(syntax))
				emit_PrimaryExpression_LeftParenthesisKeyword_0_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PrimaryExpression_LeftParenthesisKeyword_0_0_p.equals(syntax))
				emit_PrimaryExpression_LeftParenthesisKeyword_0_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' value=PrimaryExpression
	 *     (rule start) (ambiguity) 'angle' '(' value=Point
	 *     (rule start) (ambiguity) 'argument' '(' value=Point
	 *     (rule start) (ambiguity) 'e' (rule start)
	 *     (rule start) (ambiguity) 'est' (rule start)
	 *     (rule start) (ambiguity) 'i' (rule start)
	 *     (rule start) (ambiguity) 'longueur' '(' value=Point
	 *     (rule start) (ambiguity) 'nord' (rule start)
	 *     (rule start) (ambiguity) 'ouest' (rule start)
	 *     (rule start) (ambiguity) 'pi' (rule start)
	 *     (rule start) (ambiguity) 'sud' (rule start)
	 *     (rule start) (ambiguity) 'x' '(' value=Point
	 *     (rule start) (ambiguity) 'y' '(' value=Point
	 *     (rule start) (ambiguity) '~' (rule start)
	 *     (rule start) (ambiguity) Decl=[DeclarationPoint|ID]
	 *     (rule start) (ambiguity) l1=Ligne
	 *     (rule start) (ambiguity) value=NUMBER
	 *     (rule start) (ambiguity) {CoordonneeLiteral.left=}
	 *     (rule start) (ambiguity) {Degree.left=}
	 *     (rule start) (ambiguity) {Div.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multi.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 *     (rule start) (ambiguity) {Pow.left=}
	 */
	protected void emit_PrimaryExpression_LeftParenthesisKeyword_0_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' value=PrimaryExpression
	 *     (rule start) (ambiguity) 'angle' '(' value=Point
	 *     (rule start) (ambiguity) 'argument' '(' value=Point
	 *     (rule start) (ambiguity) 'e' (rule start)
	 *     (rule start) (ambiguity) 'est' (rule start)
	 *     (rule start) (ambiguity) 'i' (rule start)
	 *     (rule start) (ambiguity) 'longueur' '(' value=Point
	 *     (rule start) (ambiguity) 'nord' (rule start)
	 *     (rule start) (ambiguity) 'ouest' (rule start)
	 *     (rule start) (ambiguity) 'pi' (rule start)
	 *     (rule start) (ambiguity) 'sud' (rule start)
	 *     (rule start) (ambiguity) 'x' '(' value=Point
	 *     (rule start) (ambiguity) 'y' '(' value=Point
	 *     (rule start) (ambiguity) '~' (rule start)
	 *     (rule start) (ambiguity) Decl=[DeclarationPoint|ID]
	 *     (rule start) (ambiguity) l1=Ligne
	 *     (rule start) (ambiguity) value=NUMBER
	 *     (rule start) (ambiguity) {CoordonneeLiteral.left=}
	 *     (rule start) (ambiguity) {Degree.left=}
	 *     (rule start) (ambiguity) {Div.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multi.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 *     (rule start) (ambiguity) {Pow.left=}
	 */
	protected void emit_PrimaryExpression_LeftParenthesisKeyword_0_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
