/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.ui;

import com.google.inject.Injector;
import fr.perrin.trains.reseau.ui.internal.ReseauActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReseauExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ReseauActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ReseauActivator activator = ReseauActivator.getInstance();
		return activator != null ? activator.getInjector(ReseauActivator.FR_PERRIN_TRAINS_RESEAU) : null;
	}

}
