/*
 * generated by Xtext 2.20.0
 */
package fr.perrin.trains.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ReseauUiModule extends AbstractReseauUiModule {

	public ReseauUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
